name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev
    - uses: actions/checkout@v3
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: make test
      run: cd build && ctest --verbose
    - name: upload an artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: build/main
